<?php

return [
	'Zéro-Déchet' => 'Zéro-Déchet',
	'Agriculture' => 'Agriculture',
	'Locavore' => 'Locavore',
	'Solidarité' => 'Solidarité',
	'Ecologie' => 'Ecologie',
	'Environnement' => 'Environnement',
	'Astuces' => 'Astuces',
	'Alimentation' => 'Alimentation',
	'Consommation' => 'Consommation',
	'Bons plans' => 'Bons plans',
	'Occasion' => 'Occasion',
	'Vrac' => 'Vrac',
	'Coopération' => 'Coopération',
	'Energie' => 'Energie',
	'Santé' => 'Santé',
	'Durable' => 'Durable',
	'Recycler' => 'Recycler',
	'Développement' => 'Développement',
	'Végétariens,Végétaliens' => 'Végéta*iens',
	'Désobéissance' => 'Désobéissance',
	'Entraide' => 'Entraide',
	'Bio' => 'Bio',
	'Economie' => 'Economie',
	'Composter' => 'Composter',
	'Partage' => 'Partage',
	'Toulouse' => 'Toulouse',
];
